---
title: "netflix_original_Ridge회귀 & Lasso회귀"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, comment=NA)
```

## 데이터 정의

```{r}
rm(list=ls())

library(readxl) # readxl 패키지로 엑셀을 읽을 수 있게 해줌
netflix <- read_excel('netflix_original_종합_수정(sum)_(정량화보함).xlsx') # 넷플릭스 오리지널 엑셀데이터를 읽어옴
```

결과값의 차이를 확인해 보기 위해 종합데이터, 드라마 데이터, 영화 데이터의 회귀를 각각 돌려보았습니다

### 종합 데이터

```{r}
netflix_original <- netflix
netflix_original <- netflix_original[,c(9,15,18,32:40)] # 엑셀에서 9,15,18 과 32~40번째 열을 가져오는 것.
netflix_original <- na.omit(netflix_original) # 어떤 결측치라도 있으면 행을 제거하고 남은 데이터를 반환
netflix_original[, 4:12] <- lapply(netflix_original[, 4:12], factor) # 위에서 뽑은 12개 열중 4~12열을 계산을 편하게 만들어주고 factor 형태로 만들어줌
netflix_original[, 1:3] <- lapply(netflix_original[, 1:3], as.numeric) # Mean_Length, Director_max_award, All_rating (1~3열) 항목을 숫자형으로 변환
```

### 드라마 데이터

드라마 데이터와 영화 데이터도 위와 같은 방식인데, 행의 차이만 있음.

드라마와 영화데이터를 나눈 기준은 seasons 항목이 공백이면 영화, 값이 있으면 드라마로 분류하여 분석하였음.

```{r}
netflix_drama <- netflix[1:170,]
netflix_drama <- netflix_drama[,c(9,15,18,32:40)]
netflix_drama <- na.omit(netflix_drama)
netflix_drama[, 4:12] <- lapply(netflix_drama[, 4:12], factor)
netflix_drama[, 1:3] <- lapply(netflix_drama[, 1:3], as.numeric)
```

### 영화 데이터

```{r}
netflix_movie <- netflix[171:589,]
netflix_movie <- netflix_movie[,c(9,15,18,32:40)]
netflix_movie <- na.omit(netflix_movie)
netflix_movie[, 4:12] <- lapply(netflix_movie[, 4:12], factor)
netflix_movie[, 1:3] <- lapply(netflix_movie[, 1:3], as.numeric)
```

## Ridge회귀

### 종합 데이터

```{r}
library(glmnet)  # glmnet()
library(Metrics) # mse()
x<-model.matrix(All_rating~.,netflix_original)[,-1] #-1은 절편 1제거
y<-netflix_original$All_rating

# 교차타당도가 가장 높은 lambda 때의 회귀계수값
fit1<-glmnet(x,y,family="gaussian",alpha=0)
cv1<-cv.glmnet(x,y,family="gaussian",alpha=0)
cv1$lambda.min
coef(cv1, s = "lambda.min")

# lambda에 따른 회귀계수의 크기 변화
plot(fit1,xvar="lambda")
```

```{r}
# lambda에 따른 회귀계수의 오차 변화
# 가로축: 벌점모수(lambda)에 자연로그를 취한 값, 세로축: 이탈도
plot(cv1)
```

```{r}
ridge.fit <- glmnet(x, y, family="gaussian", alpha = 0, lambda = cv1$lambda.min)
coef(ridge.fit)
ridge.pred <- predict(ridge.fit, s = cv1$lambda.min, type = 'coefficients')
```

R\^2값

```{r}
ridge.fit$dev.ratio
```

### 드라마 데이터

```{r}
x<-model.matrix(All_rating~.,netflix_drama)[,-1] #-1은 절편 1제거
y<-netflix_drama$All_rating

# 교차타당도가 가장 높은 lambda 때의 회귀계수값
fit1<-glmnet(x,y,family="gaussian",alpha=0)
cv1<-cv.glmnet(x,y,family="gaussian",alpha=0)
cv1$lambda.min
coef(cv1, s = "lambda.min")
```

```{r}
# lambda에 따른 회귀계수의 크기 변화
plot(fit1,xvar="lambda")
```

```{r}
# lambda에 따른 회귀계수의 오차 변화
# 가로축: 벌점모수(lambda)에 자연로그를 취한 값, 세로축: 이탈도
plot(cv1)
```

```{r}
ridge.fit <- glmnet(x, y, family="gaussian", alpha = 0, lambda = cv1$lambda.min)
coef(ridge.fit)
ridge.pred <- predict(ridge.fit, s = cv1$lambda.min, type = 'coefficients')
```

R\^2값

```{r}
ridge.fit$dev.ratio
```

### 영화 데이터

```{r}
x<-model.matrix(All_rating~.,netflix_movie)[,-1] #-1은 절편 1제거
y<-netflix_movie$All_rating

# 교차타당도가 가장 높은 lambda 때의 회귀계수값
fit1<-glmnet(x,y,family="gaussian",alpha=0)
cv1<-cv.glmnet(x,y,family="gaussian",alpha=0)
cv1$lambda.min
coef(cv1, s = "lambda.min")
```

```{r}
# lambda에 따른 회귀계수의 크기 변화
plot(fit1,xvar="lambda")
```

```{r}
# lambda에 따른 회귀계수의 오차 변화
# 가로축: 벌점모수(lambda)에 자연로그를 취한 값, 세로축: 이탈도
plot(cv1)
```

```{r}
ridge.fit <- glmnet(x, y, family="gaussian", alpha = 0, lambda = cv1$lambda.min)
coef(ridge.fit)
ridge.pred <- predict(ridge.fit, s = cv1$lambda.min, type = 'coefficients')
```

R\^2값

```{r}
ridge.fit$dev.ratio
```

## Lasso회귀

### 종합데이터

```{r}
x<-model.matrix(All_rating~.,netflix_original)[,-1] #-1은 절편 1제거
y<-netflix_original$All_rating

fit2<-glmnet(x,y,family="gaussian",alpha=1)
cv2<-cv.glmnet(x,y,family="gaussian",alpha=1)
cv2$lambda.min

# lambda에 따른 회귀계수의 크기 변화
plot(fit2,xvar="norm")
```

```{r}
# lambda에 따른 회귀계수의 오차 변화
# 가로축: 벌점모수(lambda)에 자연로그를 취한 값, 세로축: 이탈도
plot(cv2)
```

```{r}
lasso.fit<-glmnet(x,y,family="gaussian",alpha=1,lambda=cv2$lambda.min)
coef(lasso.fit)
lasso.pred <- predict(lasso.fit, s = cv2$lambda.min, type = 'coefficients')
```

R\^2값

```{r}
lasso.fit$dev.ratio
```

### 드라마 데이터

```{r}
x<-model.matrix(All_rating~.,netflix_drama)[,-1] #-1은 절편 1제거
y<-netflix_drama$All_rating

fit2<-glmnet(x,y,family="gaussian",alpha=1)
cv2<-cv.glmnet(x,y,family="gaussian",alpha=1)
cv2$lambda.min

# lambda에 따른 회귀계수의 크기 변화
plot(fit2,xvar="norm")
```

```{r}
# lambda에 따른 회귀계수의 오차 변화
# 가로축: 벌점모수(lambda)에 자연로그를 취한 값, 세로축: 이탈도
plot(cv2)
```

```{r}
lasso.fit<-glmnet(x,y,family="gaussian",alpha=1,lambda=cv2$lambda.min)
coef(lasso.fit)
lasso.pred <- predict(lasso.fit, s = cv2$lambda.min, type = 'coefficients')
```

R\^2값

```{r}
lasso.fit$dev.ratio
```

### 영화 데이터

```{r}
x<-model.matrix(All_rating~.,netflix_movie)[,-1] #-1은 절편 1제거
y<-netflix_movie$All_rating

fit2<-glmnet(x,y,family="gaussian",alpha=1)
cv2<-cv.glmnet(x,y,family="gaussian",alpha=1)
cv2$lambda.min

# lambda에 따른 회귀계수의 크기 변화
plot(fit2,xvar="norm")
```

```{r}
# lambda에 따른 회귀계수의 오차 변화
# 가로축: 벌점모수(lambda)에 자연로그를 취한 값, 세로축: 이탈도
plot(cv2)
```

```{r}
lasso.fit<-glmnet(x,y,family="gaussian",alpha=1,lambda=cv2$lambda.min)
coef(lasso.fit)
lasso.pred <- predict(lasso.fit, s = cv2$lambda.min, type = 'coefficients')
```

R\^2값

```{r}
lasso.fit$dev.ratio
```
